import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Chuck Noris api next</h1>

        <p className={styles.description}>Choices your categories :</p>

        <div className={styles.grid}>
          <a href="/categories/animal" className={styles.card}>
            <h2>Animal &rarr;</h2>
          </a>

          <a href="/categories/food" className={styles.card}>
            <h2>Food &rarr;</h2>
          </a>

          <a href="categories/sport" className={styles.card}>
            <h2>Sport &rarr;</h2>
          </a>

          <a href="categories/celebrity" className={styles.card}>
            <h2>Celebrity &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
